- name: copy some dotfiles
  hosts: virtualmachines
  become: true
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /etc/X11/
        dest: /home/testing/.xinitrc
        owner: testing
        group: wheel
        mode: '0644'
