- name: Install some programs
  hosts: virtualmachines
  become: true
  tasks:
     - name: Install the 'LXDE' package group
       ansible.builtin.dnf:
         pkg:
           - '@LXDE Desktop'
           - '@LXDE Office'
         state: latest
     - name: Install alacritty
       ansible.builtin.dnf:
         pkg: alacritty
         state: latest
     - name: Install Neovim
       ansible.builtin.dnf:
         pkg: neovim
         state: latest
     - name: Install zsh
       ansible.builtin.dnf:
         pkg: zsh
         state: latest
     - name: Install git
       ansible.builtin.dnf:
         pkg: git
         state: latest
