# everything works (on Fedora server). To run:
# $ ansible-playbook -i inventory.yaml -K install.yaml

- name: install base system
  hosts: virtualmachines
  become: true
  tasks:
     - name: install a bunch of useful programs
       ansible.builtin.dnf:
         pkg:
           - alacritty
           - chromium
           - evince
           - freecad
           - git
           - inkscape
           - kicad
           - libreoffice
           - '@LXDE Desktop'
           - '@LXDE Office'
           - mpv
           - neovim
           - pulseview
           - prusa-slicer
           - rsync
           - zathura
           - zathura-djvu
           - zathura-pdf-mupdf
           - zsh
         state: latest
