- name: Transfer SSH public key
  hosts: vm-1
  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: testing
        state: present
        key: "{{ lookup('file', '/home/fedepau/.ssh/m100.pub') }}"
